In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
data = pd.read_csv('clean.csv')
data.head()

Unnamed: 0  Unnamed: 0.1  urlDrugName  effectiveness  sideEffects  \
0           0          2202            0              0            1   
1           1          3117            0              0            1   
2           2          1146            0              0            1   
3           3          3947            0              0            1   
4           4          1951            0              0            1   

   condition  benefitsReview  sideEffectsReview  commentsReview  rating_binary  
0          0               0                  0               0              0  
1          0               0                  0               0              0  
2          0               0                  0               1              1  
3          1               0                  0               0              0  
4          0               0                  0               0              0

In [3]:
data.pop('Unnamed: 0.1')
data.pop('Unnamed: 0')
data.head()

urlDrugName  effectiveness  sideEffects  condition  benefitsReview  \
0            0              0            1          0               0   
1            0              0            1          0               0   
2            0              0            1          0               0   
3            0              0            1          1               0   
4            0              0            1          0               0   

   sideEffectsReview  commentsReview  rating_binary  
0                  0               0              0  
1                  0               0              0  
2                  0               1              1  
3                  0               0              0  
4                  0               0              0

In [4]:
train_data = data.values
train_data

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0]])

In [5]:
order = np.random.permutation(len(train_data))
split = int(len(train_data)*0.8)
Train_X = train_data[order[:split]][:, :-1]
Train_Y = train_data[order[:split]][:,-1]

Test_X = train_data[order[split:]][:, :-1]
Test_Y = train_data[order[split:]][:,-1]

In [6]:
Train_Y= Train_Y.reshape(-1,1)
print(Train_Y.shape)
print(Train_X.shape )

(2485, 1)
(2485, 7)


In [33]:
class Naive():
    def __init__(self):
        pass
  
    def prob_y(self, y):
        return (np.sum(y==1))/self.m
    
    def prob_1_0(self,x,y):
        full_count = []
        for i in range(self.n):
            count = 0
            for j in range(self.m):
                if x[j,i] ==1 and y[j] ==0:
                    count+=1
            full_count.append(count)
        return (full_count)/np.sum(y==0)
    
    def prob_1_1(self,x,y):
        full_count = []
        for i in range(self.n):
            count = 0
            for j in range(self.m):
                if x[j,i] ==1 and y[j] ==1:
                    count+=1
            full_count.append(count)
        return (full_count)/np.sum(y==1)
    
    
    def Bernoulli(self,x,prob):
        return (prob**x )* ((1-prob)**(1-x))
    
    def fit(self,x,y):
        self.m, self.n = x.shape
        
        self.prob10 = self.prob_1_0(Train_X,Train_Y)
        self.prob11 = self.prob_1_1(Train_X,Train_Y)
        self.proby = self.prob_y(Train_Y)
        return self

    def pred(self,x):
        prediction = np.zeros((self.m,1))
        for i in range(self.m):
            prob0 = 1
            prob1 = 1
            for j in range(self.n):
                self.prob0 = prob0*self.Bernoulli(x[i,j],self.prob10[j])
                #print(prob_1_0.shape)
                prob1 = prob1*self.Bernoulli(x[i,j],self.prob11[j])
            prob0 = prob0 * (1-self.proby)
            prob1 = prob1 * self.proby
            prediction[i]=np.argmax([prob0,prob1])

        return prediction
    
    
    def accuracy(self,Test_Y):
        Y_pred = self.pred(x)
        Test_Y = Test_Y.reshape(-1,1)
        return np.sum(Y_pred == Test_Y) * 100/ len(Test_Y)


In [34]:
Model2 = Naive()

In [65]:
Model2.fit(Train_X, Train_Y)


In [66]:
Model2.pred(Train_X)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [50]:
def prob_y(y):
    m,n = y.shape
    py = (np.sum(y==1))/m
    return py
    

In [51]:
prob_y(Train_Y)

0.5678068410462777

In [52]:
def prob_1_0(x,y):
    m,n = x.shape
    full_count = []
    for i in range(n):
        count = 0
        for j in range(m):
            if x[j,i] ==1 and y[j] ==0:
                count+=1
        full_count.append(count)
    return (full_count)/np.sum(y==0)
            
    
            

In [53]:
prob_1_0(Train_X ,Train_Y)

array([0.00651769, 0.25977654, 1.        , 0.00837989, 0.05865922,
       0.09124767, 0.10986965])

In [54]:
def prob_1_1(x,y):
    m,n = x.shape
    full_count = []
    for i in range(n):
        count = 0
        for j in range(m):
            if x[j,i] ==1 and y[j] ==1:
                count+=1
        full_count.append(count)
    return (full_count)/np.sum(y==1)

In [55]:
prob_1_1(Train_X ,Train_Y)

array([0.01275691, 0.32459249, 1.        , 0.01700921, 0.11339476,
       0.06449327, 0.1233168 ])

In [56]:
def Bernoulli(x,prob):
    return (prob**x )* ((1-prob)**(1-x))

In [57]:
# #def fit(X,Y):
#     prob1_0 = prob_1_0(x.values,Y)
#     prob1_1 = prob_1_1(x.values,Y)
#     proby = prob_y(Y)
    
#     return prob_1_0, prob_1_1, prob_y

In [58]:
prob10 = prob_1_0(Train_X,Train_Y)
prob11 = prob_1_1(Train_X,Train_Y)
proby = prob_y(Train_Y)

In [59]:
proby

0.5678068410462777

In [60]:
def pred(x,prob10, prob11,proby):
    m,n = x.shape
    prediction = np.zeros((m,1))
    for i in range(m):
        prob0 = 1
        prob1 = 1
        for j in range(n):
            prob0 = prob0*Bernoulli(x[i,j],prob10[j])
            #print(prob_1_0.shape)
            prob1 = prob1*Bernoulli(x[i,j],prob11[j])
        prob0 = prob0 * (1-proby)
        prob1 = prob1 * proby
        prediction[i]=np.argmax([prob0,prob1])
        
    return prediction
            
            

In [61]:
prediction = pred(Test_X,prob10, prob11,proby)
prediction.sum()

583.0

In [62]:
#np.sum(prediction==y)

In [63]:
def accuracy(prediction,Test_Y):
    Test_Y = Test_Y.reshape(-1,1)
    m,n = Test_Y.shape
    return np.sum(prediction == Test_Y) * 100/ len(Test_Y)

accuracy(prediction,Test_Y)

61.41479099678457

In [64]:
#np.sum(prediction==Test_Y.reshape(-1,1))/len(Test_Y)